[KENJIN]
name = "R2Vuc2hpbiBJbXBhY3Q="
domain = "aGs0ZQ=="
base = "c29s"
id = "ZTIwMjEwMjI1MTkzMTQ4MQ=="

[BOUGAI]
name = "SG9ua2FpIEltcGFjdCAzcmQ="
domain = "cHVibGlj"
base = "bWFuaQ=="
id = "ZTIwMjExMDI5MTIwNTExMQ=="
makeup_tasks = false

[HOSHIRESSHA]
region = 'prod_official_{region}'
name = "SG9ua2FpOiBTdGFyIFJhaWw="
domain = "cHVibGlj"
base = "bHVuYS9vcw=="
id = "ZTIwMjMwMzMwMTU0MDMxMQ=="
