[[event]]
name = "Check-in"
id = "e202102251931481"
recurring = true

[[event]]
name = "Yummy! Barbecue Under the Stars"
method = "POST"
id = "e20211101bakefish"
task = "collect_fish"
start = 1635696000
end = 1636300740
url = '{id}/{task}'
success = "Collected fish: {col_fish_num}"

[event.params]
uid = '{UID}'
region = '{REGION}'
[event.json]
fir = 0

# vim: ft=toml:ts=4:et:
