name: Check-in

on:
  # Allow manual start
  workflow_dispatch:
  # Run job on 16:15UTC/00:15CST daily
  schedule:
  - cron: "15 16 * * *"

jobs:
  # check-in now
  check-in:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmubashshir/genshin-check-in@master
      with:
        id:     ${{ secrets.MHYACID }}
        uid:    ${{ secrets.REGIONAL_UID }}
        uuid:   ${{ secrets.MHYUUID }}
        region: ASIA
# vim: ft=yaml:ts=2:et:
