name: Publish Docker image

on:
  push:
    paths:
    - '**.py'
    - Dockerfile
    - poetry.lock
    - pyproject.toml
    - '**.yml'
    - games.toml

  release:
    types:
    - released

env:
  REG: codeberg.org

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event.action == 'released' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REG }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITEA_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REG }}/${{ github.repository }}
        flavor: |
          latest=false

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.REG }}/${{ github.repository }}:latest
        labels: ${{ steps.meta.outputs.labels }}

# vim: ft=yaml:ts=2:et:
